cpp :
    auth :
        authentication : true
        authorization : true
        url :
            exclude :
                - ^/portal/.*
                - ^/codetablemanager/.*
                - ^/menumanager/.*
                - ^/sysctl/.*
                - swagger
                - /v2/.*
                - /[_]mock[_]/.*
    
    
    
    
